[package]
name = "overseerd"
version = "0.1.0"
authors = ["Arnauld <arnauld.loyer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
warp = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.23"
serde_json = "1.0" 
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
rust-crypto = "^0.2"
chrono = "0.4"
# to fix similar error - https://github.com/bluss/indexmap/issues/151
indexmap = { version = "1.5.2", features = ["std"] }

