name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:  [ "v**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build the Docker image 'latest'
      run: docker build . --file Dockerfile --tag technbolts/jwtd:$(date +%s)
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Build the Docker image 'tag'
      run: docker build . --file Dockerfile --tag technbolts/jwtd:${{ steps.get_version.outputs.VERSION }}
      if: ${{ github.ref != 'refs/heads/master' }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      if: ${{ github.ref != 'refs/heads/master' }}

    - name: Push the Docker image 'tag'
      run: docker push technbolts/jwtd:${{ steps.get_version.outputs.VERSION }}
      if: ${{ github.ref != 'refs/heads/master' }}

